# Setup
title:        Blogspam
tagline:      This is my blog. Why do I have a blog? Not sure. I hate blogs.
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kyle Emmerich
  url:        https://kyle-emmerich.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
